name: pylint

on: 
  push:
    branches:[ master ]
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: 
          pip install flake8 mypy
      - name: Run flake8
        run:
          flake8 $(git ls-files '*.py')
          # flake8 src/ tests/ example. --exclude 'src/viztracer/attach_process/*' --count --ignore=W503 --max-line-length=127 --statistics
      - name: Run mypy
        run:
          mypy $(git ls-files '*.py')
          # mypy src/ --exclude 'src/viztracer/attach_process/.*'

